title: SoaPatrick

columns:
  - width: 1/3
    sections:
      box: sections/box
      log: sections/log

  - width: 1/3
    sections:
      factory: sections/factory
      pages:
        type: pages
        templates:
          - home
          - default
          - page

  - width: 1/3
    sections:
      lab: sections/lab