title: SoaPatrick

columns:
  - width: 1/3
    sections:
      Patrick:
        type: pages
        templates:
          - patrick
      pages:
        type: pages
        templates:
          - home
          - error
          - search
          - default
      box: sections/box

  - width: 1/3
    sections:
      factory: sections/factory
      likes: sections/likes

  - width: 1/3
    sections:
      lab: sections/lab
      log: sections/log