title: SoaPatrick

tabs:
  articles:
    label: Pages
    icon: page
    columns:
      - width: 1/2
        sections:
          pages:
            type: pages
            templates:
              - home
              - error
              - search
              - default
      - width: 1/2
        sections:
          Patrick:
            type: pages
            templates:
              - patrick

  box:
    label: Box
    icon: box
    columns:
      - width: 1/1
        sections:
          box: sections/box

  factory:
    label: Factory
    icon: store
    columns:
      - width: 1/1
        sections:
          factory: sections/factory

  lab:
    label: Lab
    icon: lab
    columns:
      - width: 1/1
        sections:
          lab: sections/lab

  likes:
    label: Likes
    icon: heart
    columns:
      - width: 1/1
        sections:
          likes: sections/likes

  logs:
    label: Logs
    icon: code
    columns:
      - width: 1/1
        sections:
          logs: sections/log
