title: SoaPatrick

columns:
  - width: 1/3
    sections:
      pages:
        type: pages
        templates:
          - home
          - default
          - page
      box: sections/box

  - width: 1/3
    sections:
      factory: sections/factory
      likes: sections/likes

  - width: 1/3
    sections:
      lab: sections/lab
      log: sections/log